<?php
$apiKey = "rzp_test_LX9fsSubAvp5ln";
$a = $_POST['name'];
$b = $_POST['email'];
$c = $_POST['mobile'];
$d = $_POST['subject'];

$connection = mysqli_connect("148.72.232.181:3306", "p4dtadmin", "p4dtadmin123", "P4DT_Student");

$query = mysqli_query($connection, "insert into demofaculty(name,email,mobile,subject) values('$a','$b','$c','$d')") or die("Error". mysqli_error($connection));

if($query)
{
    echo "<script>alert('Successfully Rgistered');</script>";
}

?>
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<form action="https://my2tion.com/success.html/" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amount'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="DigiVerve Technologies Pvt Ltd"
    data-description="Training & Development!"
    data-image="https://sarnadp.github.io/my2tions/logo.jpg"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['mobile'];?>"
    data-prefill.subject="<?php echo $_POST['subject'];?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

<style>
    .razorpay-payment-button { display: none; }
    </style>

    <script type="text/javascript">
        $(document).ready(function(){

            $('.razorpay-payment-button').click();
        });
        </script>
   
